const groups = {
  distance: { defaults: ['m', 'ft'], metric: ['m', 'cm', 'km'], american: ['in', 'ft', 'mi'], units: { m: ['Metros', 'm', 1], cm: ['Centímetros', 'cm', .01], km: ['Quilômetros', 'km', 1000], in: ['Inches', 'Inches (in / ")', .0254], ft: ['Feet', "Feet (ft / ')", .3048], mi: ['Miles', 'Miles (mi)', 1609.344] } },
  weight: { defaults: ['kg', 'lb'], metric: ['g', 'kg'], american: ['oz', 'lb'], units: { g: ['Gramas', 'g', .001], kg: ['Quilos', 'kg', 1], oz: ['Ounces', 'Ounces (oz)', .028349523125], lb: ['Pounds', 'Pounds (lb)', .45359237] } },
  volume: { defaults: ['l', 'floz'], metric: ['ml', 'l'], american: ['floz', 'cup'], units: { ml: ['Mililitros', 'mL', .001], l: ['Litros', 'L', 1], floz: ['Fluid ounces', 'Fluid ounces (fl oz)', .0295735295625], cup: ['Cups', 'Cups (cup)', .2365882365] } },
  temperature: { defaults: ['c', 'f'], metric: ['c'], american: ['f'], units: { c: ['Celsius', '°C', 1], f: ['Fahrenheit', 'Fahrenheit (°F)', 1] } }
};
let category = 'distance', topUnit = 'm', bottomUnit = 'ft', activeField = 'top', baseValue = null, heightMode = false;
const topInput = document.querySelector('#top-value'), bottomInput = document.querySelector('#bottom-value');
const preferenceKey = 'medidas-preferences', historyKey = 'medidas-history';
let historyTimer;
const fmt = n => Number.isFinite(n) ? Number(n.toFixed(6)).toLocaleString('pt-BR', { maximumFractionDigits: 4 }) : '';
const num = value => {
  const raw = String(value).trim().replace(/\s/g, '');
  if (!raw) return NaN;
  const comma = raw.includes(','), dot = raw.includes('.');
  if (comma && dot) {
    const decimal = raw.lastIndexOf(',') > raw.lastIndexOf('.') ? ',' : '.';
    return Number(raw.replace(decimal === ',' ? /\./g : /,/g, '').replace(decimal, '.'));
  }
  return Number(raw.replace(',', '.'));
};
function toBase(value, unit) { const g = groups[category]; return category === 'temperature' ? (unit === 'c' ? value : (value - 32) * 5 / 9) : value * g.units[unit][2]; }
function fromBase(value, unit) { const g = groups[category]; return category === 'temperature' ? (unit === 'c' ? value : value * 9 / 5 + 32) : value / g.units[unit][2]; }
function savePreferences() { localStorage.setItem(preferenceKey, JSON.stringify({ category, topUnit, bottomUnit })); }
function loadPreferences() { try { const saved = JSON.parse(localStorage.getItem(preferenceKey)); if (saved && groups[saved.category] && groups[saved.category].metric.includes(saved.topUnit) && groups[saved.category].american.includes(saved.bottomUnit)) { category = saved.category; topUnit = saved.topUnit; bottomUnit = saved.bottomUnit; } } catch {} }
function getHistory() { try { return JSON.parse(localStorage.getItem(historyKey)) || []; } catch { return []; } }
function showHistory() { const list = document.querySelector('#history-list'); const entries = getHistory(); list.innerHTML = entries.length ? entries.map(item => `<div class="history-item"><small>${item.category}</small>${item.top} ${item.topLabel} = ${item.bottom} ${item.bottomLabel}</div>`).join('') : '<div class="history-empty">Nenhuma conversão ainda.</div>'; document.querySelector('#history-panel').hidden = false; }
function saveHistory() { if (!Number.isFinite(baseValue) || !topInput.value || !bottomInput.value) return; const g = groups[category]; const entry = { category: g.label || ({ distance: 'Distância', weight: 'Peso', volume: 'Volume', temperature: 'Temperatura' })[category], top: topInput.value, bottom: bottomInput.value, topLabel: g.units[topUnit][0], bottomLabel: isHeightResult() ? 'Feet + Inches' : g.units[bottomUnit][0] }; const entries = getHistory(); const same = entries[0] && JSON.stringify(entries[0]) === JSON.stringify(entry); if (!same) localStorage.setItem(historyKey, JSON.stringify([entry, ...entries].slice(0, 5))); }
function scheduleHistory() { clearTimeout(historyTimer); historyTimer = setTimeout(saveHistory, 700); }
function formatHeight(value) { const totalInches = value / groups.distance.units.in[2]; const feet = Math.floor(totalInches / 12); const inches = Number((totalInches - feet * 12).toFixed(1)).toLocaleString('pt-BR', { maximumFractionDigits: 1 }); return `${feet} ft ${inches} in`; }
function isHeightResult() { return category === 'distance' && heightMode; }
function setResultFields() { bottomInput.readOnly = isHeightResult(); bottomInput.setAttribute('aria-label', isHeightResult() ? 'Resultado em feet e inches' : `Valor em ${groups[category].units[bottomUnit][0]}`); }
function refreshValues() { if (!Number.isFinite(baseValue)) return; topInput.value = fmt(fromBase(baseValue, topUnit)); bottomInput.value = isHeightResult() ? formatHeight(baseValue) : fmt(fromBase(baseValue, bottomUnit)); setResultFields(); }
function selectUnit(key, side) { if (side === 'top') { topUnit = key; const value = num(topInput.value); if (Number.isFinite(value)) baseValue = toBase(value, topUnit); } else { bottomUnit = key; heightMode = false; const value = num(bottomInput.value); if (Number.isFinite(value)) baseValue = toBase(value, bottomUnit); } savePreferences(); refreshValues(); renderUnits(); scheduleHistory(); }
function createUnitGroup(title, keys, side) { const g = groups[category]; const section = document.createElement('section'); section.className = 'unit-group'; const h = document.createElement('h2'); h.textContent = title; section.append(h); keys.forEach(key => { const b = document.createElement('button'); b.className = 'unit' + ((side === 'top' ? topUnit : bottomUnit) === key && !(side === 'bottom' && heightMode) ? ' selected' : ''); b.textContent = g.units[key][side === 'top' ? 0 : 1]; b.onclick = () => selectUnit(key, side); section.append(b); }); return section; }
function renderUnits() { const labels = { distance: 'Distância', weight: 'Peso', volume: 'Volume', temperature: 'Temperatura' }; document.querySelector('#app-title').textContent = `Medidas - ${labels[category]}`; const g = groups[category]; document.querySelector('#top-unit').textContent = g.units[topUnit][0]; document.querySelector('#bottom-unit').textContent = isHeightResult() ? 'Feet + Inches' : g.units[bottomUnit][0]; const list = document.querySelector('#unit-list'); list.innerHTML = ''; list.append(createUnitGroup('Métricas', g.metric, 'top')); const american = createUnitGroup('Americanas', g.american, 'bottom'); if (category === 'distance') { const height = document.createElement('button'); height.className = 'unit height-unit' + (heightMode ? ' selected' : ''); height.textContent = 'Height (ft + in)'; height.onclick = () => { const value = num(topInput.value); heightMode = true; bottomUnit = 'ft'; if (Number.isFinite(value)) baseValue = toBase(value, topUnit); savePreferences(); refreshValues(); renderUnits(); scheduleHistory(); }; american.append(height); } list.append(american); setResultFields(); }
function update(from) { const source = from === 'top' ? topInput : bottomInput, target = from === 'top' ? bottomInput : topInput; const v = num(source.value); if (!Number.isFinite(v)) { baseValue = null; target.value = ''; return; } baseValue = toBase(v, from === 'top' ? topUnit : bottomUnit); target.value = target === bottomInput && isHeightResult() ? formatHeight(baseValue) : fmt(fromBase(baseValue, from === 'top' ? bottomUnit : topUnit)); }
function chooseField(field) { activeField = field; document.querySelectorAll('.readout').forEach(x => x.classList.toggle('active', x.dataset.field === field)); }
topInput.addEventListener('input', () => { chooseField('top'); update('top'); scheduleHistory(); }); bottomInput.addEventListener('input', () => { chooseField('bottom'); update('bottom'); scheduleHistory(); }); document.querySelectorAll('.readout').forEach(x => x.addEventListener('click', () => chooseField(x.dataset.field)));
document.querySelectorAll('.category').forEach(b => b.onclick = () => { category = b.dataset.category; heightMode = false; [topUnit, bottomUnit] = groups[category].defaults; document.querySelectorAll('.category').forEach(x => x.classList.toggle('active', x === b)); baseValue = null; topInput.value = ''; bottomInput.value = ''; chooseField('top'); savePreferences(); renderUnits(); });
document.querySelector('#clear').onclick = () => { baseValue = null; topInput.value = ''; bottomInput.value = ''; chooseField('top'); topInput.focus(); };
document.querySelectorAll('[data-key]').forEach(b => b.onclick = () => { const input = activeField === 'top' ? topInput : bottomInput, key = b.dataset.key; if (key === 'delete') input.value = input.value.slice(0, -1); else if (key === '.' && input.value.includes(',')) return; else input.value += key === '.' ? ',' : key; update(activeField); scheduleHistory(); });
document.querySelector('#history-open').onclick = showHistory; document.querySelector('#history-close').onclick = () => { document.querySelector('#history-panel').hidden = true; };
loadPreferences(); document.querySelectorAll('.category').forEach(x => x.classList.toggle('active', x.dataset.category === category)); topInput.value = ''; bottomInput.value = ''; renderUnits();
if ('serviceWorker' in navigator && location.hostname !== 'localhost' && location.hostname !== '127.0.0.1') navigator.serviceWorker.register('sw.js');
document.addEventListener('dblclick', event => event.preventDefault(), { passive: false });
